import { FileResult } from './types';

export const mockResults: FileResult[] = [
    {
        id: '1',
        name: 'docker-compose.yml',
        path: 'C:\\Projects\\microservices\\docker-compose.yml',
        type: 'code',
        size: 4256,
        modified: new Date('2024-12-07T14:30:00'),
        extension: 'yml',
        preview: 'services:\n  postgres:\n    image: postgres:15\n    ports:\n      - "5432:5432"',
    },
    {
        id: '2',
        name: 'docker-compose.prod.yml',
        path: 'C:\\Projects\\webapp\\docker-compose.prod.yml',
        type: 'code',
        size: 8124,
        modified: new Date('2024-12-05T09:15:00'),
        extension: 'yml',
        preview: 'version: "3.8"\nservices:\n  api:\n    build: ./api\n    environment:\n      - NODE_ENV=production',
    },
    {
        id: '3',
        name: 'DINOv3_vs_EVA02_comparison.pdf',
        path: 'C:\\Research\\Papers\\Vision\\DINOv3_vs_EVA02_comparison.pdf',
        type: 'document',
        size: 2456789,
        modified: new Date('2024-12-01T16:45:00'),
        extension: 'pdf',
    },
    {
        id: '4',
        name: 'project-assets',
        path: 'C:\\Projects\\webapp\\public\\project-assets',
        type: 'folder',
        size: 0,
        modified: new Date('2024-12-06T11:20:00'),
    },
    {
        id: '5',
        name: 'main.py',
        path: 'C:\\Projects\\ml-pipeline\\src\\main.py',
        type: 'code',
        size: 15678,
        modified: new Date('2024-12-07T18:00:00'),
        extension: 'py',
        preview: 'import torch\nimport transformers\n\ndef train_model(config):\n    model = AutoModel.from_pretrained(...)',
    },
    {
        id: '6',
        name: 'architecture-diagram.png',
        path: 'C:\\Projects\\docs\\diagrams\\architecture-diagram.png',
        type: 'image',
        size: 456789,
        modified: new Date('2024-12-04T14:00:00'),
        extension: 'png',
    },
    {
        id: '7',
        name: 'demo-video.mp4',
        path: 'C:\\Projects\\marketing\\videos\\demo-video.mp4',
        type: 'video',
        size: 125678901,
        modified: new Date('2024-12-02T10:30:00'),
        extension: 'mp4',
    },
    {
        id: '8',
        name: 'backup-2024.zip',
        path: 'C:\\Backups\\backup-2024.zip',
        type: 'archive',
        size: 987654321,
        modified: new Date('2024-11-30T23:00:00'),
        extension: 'zip',
    },
    {
        id: '9',
        name: 'README.md',
        path: 'C:\\Projects\\verde\\README.md',
        type: 'document',
        size: 3456,
        modified: new Date('2024-12-07T20:00:00'),
        extension: 'md',
        preview: '# Verde\n\nAI-powered file search for your entire system.\n\n## Features\n- Ultra-fast indexing',
    },
    {
        id: '10',
        name: 'podcast-episode-42.mp3',
        path: 'C:\\Media\\Podcasts\\podcast-episode-42.mp3',
        type: 'audio',
        size: 45678901,
        modified: new Date('2024-11-28T08:00:00'),
        extension: 'mp3',
    },
    {
        id: '11',
        name: 'Dockerfile',
        path: 'C:\\Projects\\api-service\\Dockerfile',
        type: 'code',
        size: 1234,
        modified: new Date('2024-12-06T15:30:00'),
        extension: '',
        preview: 'FROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --only=production',
    },
    {
        id: '12',
        name: 'thesis-final-v3-FINAL.docx',
        path: 'C:\\Documents\\University\\thesis-final-v3-FINAL.docx',
        type: 'document',
        size: 8765432,
        modified: new Date('2024-11-25T22:45:00'),
        extension: 'docx',
    },
];
